### ISSUE TITLE
Can't install b3-init-scripts: there are no ebuilds to satisfy ">=sys-power/bubba-buttond-1.4-r3"

### ISSUE THREAD

**Issue by spitfire** [sakaki-/gentoo-b3-overlay#1]
emerge -av b3-init-scripts
- IMPORTANT: 7 news items need reading for repository 'gentoo'.
- Use eselect news read to view new items.

These are the packages that would be merged, in order:

Calculating dependencies... done!

emerge: there are no ebuilds to satisfy ">=sys-power/bubba-buttond-1.4-r3".
(dependency required by "sys-apps/b3-init-scripts-1.0.5::gentoo-b3" [ebuild])
(dependency required by "b3-init-scripts" [argument])

Should I look for it in another overlay?

**Comment by sakaki-** [comment]
As noted [here](https://github.com/sakaki-/gentoo-on-b3#miscellaneous-points), you can find this ebuild in Gordon's [bubba overlay](https://github.com/gordonb3/bubba-overlay/tree/master/sys-power/bubba-buttond). Best, sakaki

**Comment by sakaki-** [comment]
Closing.
